// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import { z } from "zod";
import type { HttpClient } from "../http-client.js";
import { parseResponse } from "../response.js";
import { AttachmentSchema } from "./schemas.js";
import type { Attachment } from "./types.js";

/**
 * Upload an attachment via multipart form-data.
 *
 * Requires `X-Qonto-Idempotency-Key` header (auto-generated by HttpClient).
 */
export async function uploadAttachment(
  client: HttpClient,
  file: Blob,
  fileName: string,
  options?: { readonly idempotencyKey?: string },
): Promise<Attachment> {
  const formData = new FormData();
  formData.append("file", file, fileName);

  const response = await client.postFormData("/v2/attachments", formData, options);
  return parseResponse(z.object({ attachment: AttachmentSchema }), response, "/v2/attachments").attachment;
}

/**
 * Retrieve attachment details by ID.
 */
export async function getAttachment(client: HttpClient, id: string): Promise<Attachment> {
  const endpointPath = `/v2/attachments/${encodeURIComponent(id)}`;
  const response = await client.get(endpointPath);
  return parseResponse(z.object({ attachment: AttachmentSchema }), response, endpointPath).attachment;
}

/**
 * List attachments for a transaction.
 */
export async function listTransactionAttachments(client: HttpClient, transactionId: string): Promise<Attachment[]> {
  const endpointPath = `/v2/transactions/${encodeURIComponent(transactionId)}/attachments`;
  const response = await client.get(endpointPath);
  return parseResponse(z.object({ attachments: z.array(AttachmentSchema) }), response, endpointPath).attachments;
}

/**
 * Attach a file to a transaction via multipart form-data.
 *
 * Returns the attachment details when the API includes them in the response,
 * or `undefined` when the API responds without attachment data.
 */
export async function addTransactionAttachment(
  client: HttpClient,
  transactionId: string,
  file: Blob,
  fileName: string,
  options?: { readonly idempotencyKey?: string },
): Promise<Attachment | undefined> {
  const formData = new FormData();
  formData.append("file", file, fileName);

  const endpointPath = `/v2/transactions/${encodeURIComponent(transactionId)}/attachments`;
  const response = await client.postFormData(endpointPath, formData, options);
  return parseResponse(z.object({ attachment: AttachmentSchema.optional() }), response, endpointPath).attachment;
}

/**
 * Remove all attachments from a transaction.
 */
export async function removeAllTransactionAttachments(
  client: HttpClient,
  transactionId: string,
  options?: { readonly idempotencyKey?: string },
): Promise<void> {
  await client.delete(`/v2/transactions/${encodeURIComponent(transactionId)}/attachments`, options);
}

/**
 * Remove a specific attachment from a transaction.
 */
export async function removeTransactionAttachment(
  client: HttpClient,
  transactionId: string,
  attachmentId: string,
  options?: { readonly idempotencyKey?: string },
): Promise<void> {
  await client.delete(
    `/v2/transactions/${encodeURIComponent(transactionId)}/attachments/${encodeURIComponent(attachmentId)}`,
    options,
  );
}
