// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import type { HttpClient } from "../http-client.js";
import type { Attachment } from "./types.js";

/**
 * Upload an attachment via multipart form-data.
 *
 * Requires `X-Qonto-Idempotency-Key` header (auto-generated by HttpClient).
 */
export async function uploadAttachment(
  client: HttpClient,
  file: Blob,
  fileName: string,
  options?: { readonly idempotencyKey?: string },
): Promise<Attachment> {
  const formData = new FormData();
  formData.append("file", file, fileName);

  const response = await client.postFormData<{ attachment: Attachment }>("/v2/attachments", formData, options);
  return response.attachment;
}

/**
 * Retrieve attachment details by ID.
 */
export async function getAttachment(client: HttpClient, id: string): Promise<Attachment> {
  const response = await client.get<{ attachment: Attachment }>(`/v2/attachments/${encodeURIComponent(id)}`);
  return response.attachment;
}

/**
 * List attachments for a transaction.
 */
export async function listTransactionAttachments(client: HttpClient, transactionId: string): Promise<Attachment[]> {
  const response = await client.get<{ attachments: Attachment[] }>(
    `/v2/transactions/${encodeURIComponent(transactionId)}/attachments`,
  );
  return response.attachments;
}

/**
 * Attach a file to a transaction via multipart form-data.
 */
export async function addTransactionAttachment(
  client: HttpClient,
  transactionId: string,
  file: Blob,
  fileName: string,
  options?: { readonly idempotencyKey?: string },
): Promise<Attachment> {
  const formData = new FormData();
  formData.append("file", file, fileName);

  const response = await client.postFormData<{ attachment: Attachment }>(
    `/v2/transactions/${encodeURIComponent(transactionId)}/attachments`,
    formData,
    options,
  );
  return response.attachment;
}

/**
 * Remove all attachments from a transaction.
 */
export async function removeAllTransactionAttachments(
  client: HttpClient,
  transactionId: string,
  options?: { readonly idempotencyKey?: string },
): Promise<void> {
  await client.delete(`/v2/transactions/${encodeURIComponent(transactionId)}/attachments`, options);
}

/**
 * Remove a specific attachment from a transaction.
 */
export async function removeTransactionAttachment(
  client: HttpClient,
  transactionId: string,
  attachmentId: string,
  options?: { readonly idempotencyKey?: string },
): Promise<void> {
  await client.delete(
    `/v2/transactions/${encodeURIComponent(transactionId)}/attachments/${encodeURIComponent(attachmentId)}`,
    options,
  );
}
